app:
  title: "FastAPI onion template"
  version: "1.0"
  root_path: "/api/v1"
  port: 8000

auth:
  private_key_path: "abspath/to/certs/private.pem"
  public_key_path: "abspath/to/certs/public.pem"
  algorithm: "RS256"
  access_token_expire_minutes: 15
  refresh_token_expire_days: 30

database:
  url: "sqlite+aiosqlite:///backend/database/db.sqlite3"

query:
  default_page: 1
  default_limit: 10
  max_limit: 100