# User Credentials

USERNAME_MIN_LENGTH = 2
USERNAME_MAX_LENGTH = 16
EMAIL_MAX_LENGTH = 255
NAME_MIN_LENGTH = 1
NAME_MAX_LENGTH = 32
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 32
PASSWORD_HASH_MAX_LENGTH = 128
